export const RECONCILIATION_RULES = Object.freeze(Object.seal({
  REPLACE: 'REPLACE',
  BYPATH: 'BYPATH',
  BYPATH_ONCE: 'BYPATH_ONCE',
  BYPATH_CHILDREN: 'BYPATH_CHILDREN',
  BYPATH_CHILDREN_ONCE: 'BYPATH_CHILDREN_ONCE',
  BYPATH_LISTENERS: 'BYPATH_LISTENERS',
  BYPATH_LISTENERS_ONCE: 'BYPATH_LISTENERS_ONCE'
}))
